name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        python-version: [3.7]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest mypy black isort flake8
    
    - name: Run pytest
      run: pytest module_29_testing/hw/tests/
    
    - name: Run isort
      run: isort --check-only module_29_testing/hw/flaskr/
    
    - name: Run flake8
      run: flake8 module_29_testing/hw/flaskr/

    - name: Run black
      run: black --diff --check -l79 module_29_testing/hw/flaskr/

    - name: Check if config exists
      run: |
        if [ -f mypy.ini ]; then
          echo "mypy.ini found"
        else 
          echo "mypy.ini not found"
        fi

    - name: Run mypy
      run:  | 
        cd module_29_testing/hw/flaskr/
        mypy -v .
